---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wordpress-pg # Название кластера.
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    #storageClass: local
    size: 1Gi
  bootstrap:
    initdb: # Развертывание нового кластера.
      database: wordpress
      owner: wordpress
      secret:
        name: wordpress-pass
  postgresql:
    parameters:
      max_worker_processes: "60"
    pg_hba:
      # To access through TCP/IP you will need to get username
      # and password from the secret cluster-example-custom-app
      - host all all all trust

